language : java 
sudo : false
script: "mvn -f RestAPIOrnek/pom.xml install cobertura:cobertura"
jdk:
   - oraclejdk8
after_success: 
  -bash <(curl -s https://codecov.io/bash)
  env:
  global:
    - CODECOV_TOKEN="218a8e82-d830-491c-82dc-2e59e992c297"
